// 生成 Cocos 工程资源：脚本 meta / 场景 meta / Main.scene
// 用法：node gen_project.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const KEYS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function compressUuid(uuid) {
    const hex = uuid.replace(/-/g, '');
    let out = hex.slice(0, 5);
    for (let i = 5; i < 32; i += 3) {
        const v = parseInt(hex.substr(i, 3), 16);
        out += KEYS[v >> 6] + KEYS[v & 63];
    }
    return out;
}

const root = __dirname;
const scriptsDir = path.join(root, 'assets', 'scripts');
const scripts = ['Config', 'Theme', 'BattleView', 'ForgePanel', 'ItemBar', 'Modals', 'GameApp', 'EnemyConfig', 'TowerConfig', 'StageConfig', 'MonsterTableConfig'];

function writeMeta(file, obj) {
    fs.writeFileSync(file, JSON.stringify(obj, null, 2) + '\n');
}

// 1. 脚本 meta
const uuids = {};
for (const s of scripts) {
    const uuid = crypto.randomUUID();
    uuids[s] = uuid;
    writeMeta(path.join(scriptsDir, s + '.ts.meta'), {
        ver: '4.0.23', importer: 'typescript', imported: true,
        uuid, files: [], subMetas: {}, userData: {},
    });
}

// 2. scripts 目录 meta
writeMeta(path.join(root, 'assets', 'scripts.meta'), {
    ver: '1.2.0', importer: 'directory', imported: true,
    uuid: crypto.randomUUID(), files: [], subMetas: {}, userData: {},
});

// 3. 场景 + meta
const sceneUuid = crypto.randomUUID();
writeMeta(path.join(root, 'assets', 'Main.scene.meta'), {
    ver: '1.1.45', importer: 'scene', imported: true,
    uuid: sceneUuid, files: ['.json'], subMetas: {}, userData: {},
});

const gameAppCompressed = compressUuid(uuids.GameApp);
const scene = [
    '[',
    '  {',
    '    "__type__": "cc.SceneAsset",',
    '    "_name": "Main",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "_native": "",',
    '    "scene": { "__id__": 1 }',
    '  },',
    '  {',
    '    "__type__": "cc.Scene",',
    '    "_name": "Main",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "_parent": null,',
    '    "_children": [{ "__id__": 2 }],',
    '    "_active": true,',
    '    "_components": [],',
    '    "_prefab": null,',
    '    "_lpos": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 0 },',
    '    "_lrot": { "__type__": "cc.Quat", "x": 0, "y": 0, "z": 0, "w": 1 },',
    '    "_lscale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },',
    '    "_mobility": 0,',
    '    "_layer": 1073741824,',
    '    "_euler": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 0 },',
    '    "autoReleaseAssets": false,',
    `    "_globals": { "__id__": 8 },`,
    `    "_id": "${sceneUuid}"`,
    '  },',
    '  {',
    '    "__type__": "cc.Node",',
    '    "_name": "Canvas",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "_parent": { "__id__": 1 },',
    '    "_children": [{ "__id__": 3 }],',
    '    "_active": true,',
    '    "_components": [{ "__id__": 5 }, { "__id__": 6 }, { "__id__": 7 }],',
    '    "_prefab": null,',
    '    "_lpos": { "__type__": "cc.Vec3", "x": 195, "y": 422, "z": 0 },',
    '    "_lrot": { "__type__": "cc.Quat", "x": 0, "y": 0, "z": 0, "w": 1 },',
    '    "_lscale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },',
    '    "_mobility": 0,',
    '    "_layer": 33554432,',
    '    "_euler": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 0 },',
    '    "_id": "8b6c7d9e-1a2b-4c3d-b5e6-7a8b9c0d1e2f"',
    '  },',
    '  {',
    '    "__type__": "cc.Node",',
    '    "_name": "Camera",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "_parent": { "__id__": 2 },',
    '    "_children": [],',
    '    "_active": true,',
    '    "_components": [{ "__id__": 4 }],',
    '    "_prefab": null,',
    '    "_lpos": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 1000 },',
    '    "_lrot": { "__type__": "cc.Quat", "x": 0, "y": 0, "z": 0, "w": 1 },',
    '    "_lscale": { "__type__": "cc.Vec3", "x": 1, "y": 1, "z": 1 },',
    '    "_mobility": 0,',
    '    "_layer": 1073741824,',
    '    "_euler": { "__type__": "cc.Vec3", "x": 0, "y": 0, "z": 0 },',
    '    "_id": "7a5b6c8d-9e0f-4a1b-8c2d-3b4c5d6e7f8a"',
    '  },',
    '  {',
    '    "__type__": "cc.Camera",',
    '    "_name": "",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "node": { "__id__": 3 },',
    '    "_enabled": true,',
    '    "__prefab": null,',
    '    "_projection": 0,',
    '    "_priority": 1073741824,',
    '    "_fov": 45,',
    '    "_fovAxis": 0,',
    '    "_orthoHeight": 422,',
    '    "_near": 1,',
    '    "_far": 2000,',
    '    "_color": { "__type__": "cc.Color", "r": 18, "g": 18, "b": 31, "a": 255 },',
    '    "_depth": 1,',
    '    "_stencil": 0,',
    '    "_clearFlags": 7,',
    '    "_rect": { "__type__": "cc.Rect", "x": 0, "y": 0, "width": 1, "height": 1 },',
    '    "_aperture": 19,',
    '    "_shutter": 7,',
    '    "_iso": 0,',
    '    "_screenScale": 1,',
    '    "_visibility": 41943040,',
    '    "_targetTexture": null,',
    '    "_postProcess": null,',
    '    "_usePostProcess": false,',
    '    "_cameraType": -1,',
    '    "_trackingType": 0,',
    '    "_id": "e08WJVo7tIjIdNijShpgO5"',
    '  },',
    '  {',
    '    "__type__": "cc.UITransform",',
    '    "_name": "",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "node": { "__id__": 2 },',
    '    "_enabled": true,',
    '    "__prefab": null,',
    '    "_contentSize": { "__type__": "cc.Size", "width": 390, "height": 844 },',
    '    "_anchorPoint": { "__type__": "cc.Vec2", "x": 0.5, "y": 0.5 },',
    '    "_id": "b2bffaCjBGkrlM4KDroiZq"',
    '  },',
    '  {',
    '    "__type__": "cc.Canvas",',
    '    "_name": "",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "node": { "__id__": 2 },',
    '    "_enabled": true,',
    '    "__prefab": null,',
    '    "cameraComponent": { "__id__": 4 },',
    '    "_alignCanvasWithScreen": true,',
    '    "_id": "14QkTxE09P6JpQYB8Sar5D"',
    '  },',
    '  {',
    `    "__type__": "${gameAppCompressed}",`,
    '    "_name": "",',
    '    "_objFlags": 0,',
    '    "__editorExtras__": {},',
    '    "node": { "__id__": 2 },',
    '    "_enabled": true,',
    '    "__prefab": null,',
    '    "_id": "694VqxmY1O7KhtuGHd8kgr"',
    '  },',
    '  {',
    '    "__type__": "cc.SceneGlobals",',
    '    "ambient": { "__id__": 9 },',
    '    "shadows": { "__id__": 10 },',
    '    "_skybox": { "__id__": 11 },',
    '    "fog": { "__id__": 12 },',
    '    "octree": { "__id__": 13 },',
    '    "skin": { "__id__": 14 },',
    '    "lightProbeInfo": { "__id__": 15 },',
    '    "bakedWithStationaryMainLight": false,',
    '    "bakedWithHighpLightmap": false',
    '  },',
    '  {',
    '    "__type__": "cc.AmbientInfo",',
    '    "_skyColorHDR": { "__type__": "cc.Vec4", "x": 0.2, "y": 0.5, "z": 0.8, "w": 0.520833125 },',
    '    "_skyColor": { "__type__": "cc.Vec4", "x": 0.2, "y": 0.5, "z": 0.8, "w": 0.520833125 },',
    '    "_skyIllumHDR": 20000,',
    '    "_skyIllum": 20000,',
    '    "_groundAlbedoHDR": { "__type__": "cc.Vec4", "x": 0.2, "y": 0.2, "z": 0.2, "w": 1 },',
    '    "_groundAlbedo": { "__type__": "cc.Vec4", "x": 0.2, "y": 0.2, "z": 0.2, "w": 1 },',
    '    "_skyColorLDR": { "__type__": "cc.Vec4", "x": 0.441788375377655, "y": 0.713536858558655, "z": 1, "w": 0.803921568627451 },',
    '    "_skyIllumLDR": 0.8,',
    '    "_groundAlbedoLDR": { "__type__": "cc.Vec4", "x": 0.0941176470588235, "y": 0.32156862745098, "z": 0.227450980392157, "w": 1 }',
    '  },',
    '  {',
    '    "__type__": "cc.ShadowsInfo",',
    '    "_enabled": false,',
    '    "_type": 0,',
    '    "_normal": { "__type__": "cc.Vec3", "x": 0, "y": 1, "z": 0 },',
    '    "_distance": 0,',
    '    "_shadowColor": { "__type__": "cc.Color", "r": 76, "g": 76, "b": 76, "a": 255 },',
    '    "_maxReceived": 4,',
    '    "_size": { "__type__": "cc.Vec2", "x": 1024, "y": 1024 }',
    '  },',
    '  {',
    '    "__type__": "cc.SkyboxInfo",',
    '    "_envLightingType": 0,',
    '    "_envmapHDR": null,',
    '    "_envmap": null,',
    '    "_envmapLDR": null,',
    '    "_diffuseMapHDR": null,',
    '    "_diffuseMapLDR": null,',
    '    "_enabled": false,',
    '    "_useHDR": true,',
    '    "_editableMaterial": null,',
    '    "_reflectionHDR": null,',
    '    "_reflectionLDR": null,',
    '    "_rotationAngle": 0',
    '  },',
    '  {',
    '    "__type__": "cc.FogInfo",',
    '    "_type": 0,',
    '    "_fogColor": { "__type__": "cc.Color", "r": 200, "g": 200, "b": 200, "a": 255 },',
    '    "_enabled": false,',
    '    "_fogDensity": 0.3,',
    '    "_fogStart": 0.5,',
    '    "_fogEnd": 300,',
    '    "_fogAtten": 5,',
    '    "_fogTop": 1.5,',
    '    "_fogRange": 1.2,',
    '    "_accurate": false',
    '  },',
    '  {',
    '    "__type__": "cc.OctreeInfo",',
    '    "_enabled": false,',
    '    "_minPos": { "__type__": "cc.Vec3", "x": -1024, "y": -1024, "z": -1024 },',
    '    "_maxPos": { "__type__": "cc.Vec3", "x": 1024, "y": 1024, "z": 1024 },',
    '    "_depth": 8',
    '  },',
    '  {',
    '    "__type__": "cc.SkinInfo",',
    '    "_enabled": true,',
    '    "_blurRadius": 0.01,',
    '    "_sssIntensity": 3',
    '  },',
    '  {',
    '    "__type__": "cc.LightProbeInfo",',
    '    "_giScale": 1,',
    '    "_giSamples": 1024,',
    '    "_bounces": 2,',
    '    "_reduceRinging": 0,',
    '    "_showProbe": true,',
    '    "_showWireframe": true,',
    '    "_showConvex": false,',
    '    "_data": null,',
    '    "_lightProbeSphereVolume": 1',
    '  }',
    ']',
].join('\n');
fs.writeFileSync(path.join(root, 'assets', 'Main.scene'), scene + '\n');

console.log('Generated:', scripts.map(s => s + '.ts.meta').join(', '),
    '| scripts.meta | Main.scene + meta');
console.log('GameApp compressed uuid:', gameAppCompressed);
